name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/django-shortuuid
    permissions:
      id-token: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Build wheel"
        run: uv build

      - name: "Publish package"
        run: uv publish
